[maven]
path = "D:\\"
projectName = "hshc-mqmanager"
fileSeperator = "\\"
groupId = "com.hshc.mqmanager"
artifactId = "hshc-mqmanager"

[bill]
dbuser = "fcar_loan"
dbpwd = "fcar_loan"
ddurl = "10.104.50.41:3306"
dbname = "fcar_loan"
