[maven]
path = "d:/Users/zhangyong/go/mydelay-store/"
projectName = "mydelay-store"
fileSeperator = "/"
groupId = "com.zy.code.sublime"
artifactId = "code-sublime"

[bill]
dbuser = "fcar_loan"
dbpwd = "fcar_loan"
ddurl = "10.104.50.41:3306"
dbname = "fcar_loan"
