[maven]
path = "/Users/zhangyong/go/code-sublime"
projectName = "code-sublime"
fileSeperator = "/"
groupId = "com.zy.code.sublime"
artifactId = "code-sublime"

[bill]
dbuser = "fcar_loan"
dbpwd = "fcar_loan"
ddurl = "10.104.50.41:3306"
dbname = "fcar_loan"
