[maven]
path = "/Users/zhangyong/Downloads/"
projectName = "spring-cache-demo"
moduleNamePrefix = "cache-demo"
groupId = "com.courage.spring"
basePackage = "com.courage.spring.cache"
## 是否 dubbo 版本
isDubbo = "0"