[maven]
path = "D:\\workspace\\jianpeijianguan"
projectName = "supervise-dubbo-all"
moduleNamePrefix = "supervise-dubbo"
groupId = "com.courage.training"
basePackage = "com.courage.training.supervise.dubbo"