[maven]
path = "/Users/zhangyong/Downloads/"
projectName = "shardingsphere-jdbc-demo"
moduleNamePrefix = "shardingsphere-jdbc"
groupId = "com.courage."
basePackage = "com.courage.shardingsphere.jdbc"
## 是否 dubbo 版本
isDubbo = "0"
