spring:
  profiles:
    active: test
  application:
    name: {{.ModuleNamePrefix}}-server

server:
  port: 9793
  servlet:
    context-path: /{{.ModuleNamePrefix}}-server

pagehelper:
  supportMethodsArguments: true
  reasonable: false
  helperDialect: mysql
  params: count=countSql

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: {{.BasePackage}}.domain.po

